// ----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------

// Namespace và các using cần thiết cho Designer
using System.Drawing;
using System.Windows.Forms;
using MaterialSkin;
using MaterialSkin.Controls;
// KHÔNG CẦN using System; using System.IO; using System.Diagnostics; ở đây cho logic tải ảnh

namespace GUI // Thay thế bằng namespace thực tế của bạn
{
    partial class frmLogin // Đảm bảo kế thừa từ MaterialForm trong frmLogin.cs
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            // Khởi tạo các control
            this.pictureBoxLoginImage = new System.Windows.Forms.PictureBox(); // Ảnh bên trái
            this.cardLoginArea = new MaterialSkin.Controls.MaterialCard(); // Khu vực đăng nhập bên phải
            this.lblLoginTitle = new MaterialSkin.Controls.MaterialLabel(); // Tiêu đề "Đăng nhập"
            this.btnQuenMatKhau = new MaterialSkin.Controls.MaterialButton();
            this.btnThoat = new MaterialSkin.Controls.MaterialButton();
            this.btnLogin = new MaterialSkin.Controls.MaterialButton();
            this.chkShowPassword = new MaterialSkin.Controls.MaterialCheckbox();
            this.txtPassword = new MaterialSkin.Controls.MaterialTextBox2();
            this.txtUsername = new MaterialSkin.Controls.MaterialTextBox2();

            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLoginImage)).BeginInit();
            this.cardLoginArea.SuspendLayout(); // Bắt đầu định nghĩa nội dung trong Card bên phải
            this.SuspendLayout();

            //
            // pictureBoxLoginImage: Ảnh nền bên trái
            //
            // MÀU NỀN TẠM THỜI CÓ THỂ ĐẶT Ở ĐÂY HOẶC TRONG CODE-BEHIND
            // this.pictureBoxLoginImage.BackColor = System.Drawing.Color.Gray; 
            this.pictureBoxLoginImage.Dock = System.Windows.Forms.DockStyle.Left; // Neo vào bên trái

            // --- ĐOẠN CODE TẢI ẢNH (TRY...CATCH) ĐÃ ĐƯỢC CHUYỂN SANG frmLogin.cs ---
            // Lý do: InitializeComponent chỉ nên chứa code do Designer tạo ra
            // Logic tải ảnh nên đặt trong Constructor hoặc sự kiện Load của Form

            this.pictureBoxLoginImage.Location = new System.Drawing.Point(3, 64); // Vị trí bắt đầu dưới thanh tiêu đề MaterialForm
            this.pictureBoxLoginImage.Name = "pictureBoxLoginImage";
            this.pictureBoxLoginImage.Size = new System.Drawing.Size(350, 483); // Chiều rộng ảnh, chiều cao sẽ theo Form
            this.pictureBoxLoginImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage; // Chế độ hiển thị ảnh
            this.pictureBoxLoginImage.TabIndex = 0;
            this.pictureBoxLoginImage.TabStop = false;

            //
            // cardLoginArea: Khu vực chứa controls đăng nhập bên phải
            //
            this.cardLoginArea.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.cardLoginArea.Controls.Add(this.lblLoginTitle);
            this.cardLoginArea.Controls.Add(this.btnQuenMatKhau);
            this.cardLoginArea.Controls.Add(this.btnThoat);
            this.cardLoginArea.Controls.Add(this.btnLogin);
            this.cardLoginArea.Controls.Add(this.chkShowPassword);
            this.cardLoginArea.Controls.Add(this.txtPassword);
            this.cardLoginArea.Controls.Add(this.txtUsername);
            this.cardLoginArea.Depth = 0;
            this.cardLoginArea.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cardLoginArea.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.cardLoginArea.Location = new System.Drawing.Point(353, 64);
            this.cardLoginArea.Margin = new System.Windows.Forms.Padding(0);
            this.cardLoginArea.MouseState = MaterialSkin.MouseState.HOVER;
            this.cardLoginArea.Name = "cardLoginArea";
            this.cardLoginArea.Padding = new System.Windows.Forms.Padding(25, 30, 25, 25);
            this.cardLoginArea.Size = new System.Drawing.Size(444, 483);
            this.cardLoginArea.TabIndex = 1;

            //
            // lblLoginTitle: Tiêu đề "ĐĂNG NHẬP" trong Card
            //
            this.lblLoginTitle.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lblLoginTitle.Depth = 0;
            this.lblLoginTitle.Font = new System.Drawing.Font("Roboto", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.lblLoginTitle.FontType = MaterialSkin.MaterialSkinManager.fontType.H5;
            this.lblLoginTitle.Location = new System.Drawing.Point(122, 35); // Điều chỉnh vị trí nếu cần
            this.lblLoginTitle.MouseState = MaterialSkin.MouseState.HOVER;
            this.lblLoginTitle.Name = "lblLoginTitle";
            this.lblLoginTitle.Size = new System.Drawing.Size(200, 40);
            this.lblLoginTitle.TabIndex = 6;
            this.lblLoginTitle.Text = "ĐĂNG NHẬP";
            this.lblLoginTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblLoginTitle.HighEmphasis = true;

            //
            // txtUsername: Ô nhập tên đăng nhập (trong Card)
            //
            this.txtUsername.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtUsername.AnimateReadOnly = false;
            this.txtUsername.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.txtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsername.Depth = 0;
            this.txtUsername.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtUsername.HideSelection = true;
            this.txtUsername.Hint = "Tên đăng nhập";
            this.txtUsername.LeadingIcon = null;
            this.txtUsername.Location = new System.Drawing.Point(28, 100);
            this.txtUsername.Margin = new System.Windows.Forms.Padding(3, 3, 3, 15);
            this.txtUsername.MaxLength = 50;
            this.txtUsername.MouseState = MaterialSkin.MouseState.OUT;
            this.txtUsername.Name = "txtUsername";
            this.txtUsername.PasswordChar = '\0';
            this.txtUsername.PrefixSuffixText = null;
            this.txtUsername.ReadOnly = false;
            this.txtUsername.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtUsername.SelectedText = "";
            this.txtUsername.SelectionLength = 0;
            this.txtUsername.SelectionStart = 0;
            this.txtUsername.ShortcutsEnabled = true;
            this.txtUsername.Size = new System.Drawing.Size(388, 48);
            this.txtUsername.TabIndex = 0;
            this.txtUsername.TabStop = true;
            this.txtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsername.TrailingIcon = null;
            this.txtUsername.UseSystemPasswordChar = false;
            this.txtUsername.UseTallSize = true;

            //
            // txtPassword: Ô nhập mật khẩu (trong Card)
            //
            this.txtPassword.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPassword.AnimateReadOnly = false;
            this.txtPassword.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Depth = 0;
            this.txtPassword.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtPassword.HideSelection = true;
            this.txtPassword.Hint = "Mật khẩu";
            this.txtPassword.LeadingIcon = null;
            this.txtPassword.Location = new System.Drawing.Point(28, 165);
            this.txtPassword.Margin = new System.Windows.Forms.Padding(3, 3, 3, 15);
            this.txtPassword.MaxLength = 50;
            this.txtPassword.MouseState = MaterialSkin.MouseState.OUT;
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.PasswordChar = '●';
            this.txtPassword.PrefixSuffixText = null;
            this.txtPassword.ReadOnly = false;
            this.txtPassword.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(388, 48);
            this.txtPassword.TabIndex = 1;
            this.txtPassword.TabStop = true;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TrailingIcon = null;
            this.txtPassword.UseSystemPasswordChar = true; // Sử dụng ký tự hệ thống
            this.txtPassword.UseTallSize = true;
            this.txtPassword.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtPassword_KeyDown); // Giữ lại sự kiện

            //
            // chkShowPassword: Checkbox hiện/ẩn mật khẩu (trong Card)
            //
            this.chkShowPassword.AutoSize = true;
            this.chkShowPassword.Depth = 0;
            this.chkShowPassword.Location = new System.Drawing.Point(25, 230);
            this.chkShowPassword.Margin = new System.Windows.Forms.Padding(0);
            this.chkShowPassword.MouseLocation = new System.Drawing.Point(-1, -1);
            this.chkShowPassword.MouseState = MaterialSkin.MouseState.HOVER;
            this.chkShowPassword.Name = "chkShowPassword";
            this.chkShowPassword.ReadOnly = false;
            this.chkShowPassword.Ripple = true;
            this.chkShowPassword.Size = new System.Drawing.Size(136, 37);
            this.chkShowPassword.TabIndex = 2;
            this.chkShowPassword.Text = "Hiện mật khẩu";
            this.chkShowPassword.UseVisualStyleBackColor = true;
            this.chkShowPassword.CheckedChanged += new System.EventHandler(this.chkShowPassword_CheckedChanged); // Giữ lại sự kiện

            //
            // btnQuenMatKhau: Nút Quên mật khẩu (trong Card)
            //
            this.btnQuenMatKhau.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnQuenMatKhau.AutoSize = false;
            this.btnQuenMatKhau.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnQuenMatKhau.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnQuenMatKhau.Depth = 0;
            this.btnQuenMatKhau.HighEmphasis = false;
            this.btnQuenMatKhau.Icon = null;
            this.btnQuenMatKhau.Location = new System.Drawing.Point(240, 230);
            this.btnQuenMatKhau.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnQuenMatKhau.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnQuenMatKhau.Name = "btnQuenMatKhau";
            this.btnQuenMatKhau.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnQuenMatKhau.Size = new System.Drawing.Size(170, 36);
            this.btnQuenMatKhau.TabIndex = 3;
            this.btnQuenMatKhau.Text = "Quên mật khẩu?";
            this.btnQuenMatKhau.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Text;
            this.btnQuenMatKhau.UseAccentColor = false;
            this.btnQuenMatKhau.UseVisualStyleBackColor = true;
            this.btnQuenMatKhau.Click += new System.EventHandler(this.btnQuenMatKhau_Click); // Giữ lại sự kiện

            //
            // btnLogin: Nút Đăng nhập (trong Card) - Đặt ở dưới cùng
            //
            this.btnLogin.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnLogin.AutoSize = false;
            this.btnLogin.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnLogin.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnLogin.Depth = 0;
            this.btnLogin.HighEmphasis = true;
            this.btnLogin.Icon = null;
            this.btnLogin.Location = new System.Drawing.Point(28, 350); // Điều chỉnh vị trí nếu cần
            this.btnLogin.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnLogin.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnLogin.Size = new System.Drawing.Size(388, 36);
            this.btnLogin.TabIndex = 4;
            this.btnLogin.Text = "Đăng Nhập";
            this.btnLogin.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
            this.btnLogin.UseAccentColor = true;
            this.btnLogin.UseVisualStyleBackColor = true;
            this.btnLogin.Click += new System.EventHandler(this.btnLogin_Click); // Giữ lại sự kiện

            //
            // btnThoat: Nút Thoát (trong Card) - Đặt dưới nút Đăng nhập
            //
            this.btnThoat.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnThoat.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnThoat.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnThoat.Depth = 0;
            this.btnThoat.HighEmphasis = false;
            this.btnThoat.Icon = null;
            this.btnThoat.Location = new System.Drawing.Point(347, 405); // Điều chỉnh vị trí nếu cần
            this.btnThoat.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnThoat.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnThoat.Name = "btnThoat";
            this.btnThoat.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnThoat.Size = new System.Drawing.Size(67, 36);
            this.btnThoat.TabIndex = 5;
            this.btnThoat.Text = "Thoát";
            this.btnThoat.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Text;
            this.btnThoat.UseAccentColor = false;
            this.btnThoat.UseVisualStyleBackColor = true;
            this.btnThoat.Click += new System.EventHandler(this.btnThoat_Click); // Giữ lại sự kiện


            //
            // frmLogin: Cấu hình Form chính
            //
            this.AcceptButton = this.btnLogin;
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.btnThoat;
            this.ClientSize = new System.Drawing.Size(800, 550); // Kích thước form
            this.Controls.Add(this.cardLoginArea);
            this.Controls.Add(this.pictureBoxLoginImage);
            this.DrawerShowIconsWhenHidden = true;
            this.DrawerTabControl = null;
            this.MaximizeBox = false;
            this.MinimizeBox = true;
            this.MinimumSize = new System.Drawing.Size(700, 500);
            this.Name = "frmLogin";
            this.Padding = new System.Windows.Forms.Padding(3, 64, 3, 3);
            this.Sizable = true; // Cho phép resize
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Đăng Nhập Hệ Thống";
            this.Load += new System.EventHandler(this.frmLogin_Load); // Giữ lại sự kiện Load
            // this.Resize += new System.EventHandler(this.frmLogin_Resize); // Không cần nữa

            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxLoginImage)).EndInit();
            this.cardLoginArea.ResumeLayout(false);
            this.cardLoginArea.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        // Khai báo các biến control (GIỮ NGUYÊN)
        private System.Windows.Forms.PictureBox pictureBoxLoginImage;
        private MaterialSkin.Controls.MaterialCard cardLoginArea;
        private MaterialSkin.Controls.MaterialLabel lblLoginTitle;
        private MaterialSkin.Controls.MaterialButton btnQuenMatKhau;
        private MaterialSkin.Controls.MaterialButton btnThoat;
        private MaterialSkin.Controls.MaterialButton btnLogin;
        private MaterialSkin.Controls.MaterialCheckbox chkShowPassword;
        private MaterialSkin.Controls.MaterialTextBox2 txtPassword;
        private MaterialSkin.Controls.MaterialTextBox2 txtUsername;
    }
}