// File: GUI/ucQuanLyDocGia.Designer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Project/Namespace: GUI

using System;
using System.Windows.Forms; // Needed for various control types, AutoScaleMode, SizeF, Point, EventArgs, DockStyle, Keys, DataGridView etc.
using MaterialSkin.Controls; // Needed for MaterialTextBox2, MaterialButton, MaterialCheckbox, MaterialSkin.MouseState
using System.Drawing; // Needed for Point, Size, Color
using System.ComponentModel; // Needed for IContainer, ComponentResourceManager
using System.Collections.Generic; // Needed for List (if used in DataSource)

namespace GUI // Namespace of your GUI project
{
    partial class ucQuanLyDocGia
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        // --- DECLARE UI CONTROLS (Partial Class Members) ---
        // Panel for input details
        private System.Windows.Forms.Panel panelDetails;
        private MaterialSkin.Controls.MaterialTextBox2 txtId;
        private MaterialSkin.Controls.MaterialTextBox2 txtMaDocGia;
        private MaterialSkin.Controls.MaterialTextBox2 txtTenDocGia;
        private MaterialSkin.Controls.MaterialTextBox2 txtDienThoai;
        private System.Windows.Forms.DateTimePicker dtpNgaySinh;
        private MaterialSkin.Controls.MaterialTextBox2 txtDiaChi;
        private MaterialSkin.Controls.MaterialTextBox2 txtEmail;
        private System.Windows.Forms.ComboBox cboLoaiDocGia; // Using standard ComboBox for now, can switch to Material if needed
        private MaterialSkin.Controls.MaterialTextBox2 txtTenDangNhap;
        private MaterialSkin.Controls.MaterialTextBox2 txtMatKhau;
        private System.Windows.Forms.DateTimePicker dtpNgayLapThe;
        private System.Windows.Forms.DateTimePicker dtpNgayHetHan;
        private MaterialSkin.Controls.MaterialTextBox2 txtTienNo;
        private MaterialSkin.Controls.MaterialTextBox2 txtSoTienThu; // For 'Số tiền thu'
        private MaterialSkin.Controls.MaterialButton btnThuTienPhat; // Button to 'Thu phạt'
        private MaterialSkin.Controls.MaterialButton btnLuu;
        private MaterialSkin.Controls.MaterialButton btnBoQua;

        // Panel for grid, actions, filters, search
        private System.Windows.Forms.Panel panelGrid;
        private MaterialSkin.Controls.MaterialButton btnThem;
        private MaterialSkin.Controls.MaterialButton btnSua;
        private MaterialSkin.Controls.MaterialButton btnXoa;
        private MaterialSkin.Controls.MaterialButton btnKhoiPhuc; // Button to 'Phục hồi'
        private MaterialSkin.Controls.MaterialButton btnXemLichSu; // Button to 'Xem Lịch sử'
        private MaterialSkin.Controls.MaterialButton btnXemChiTietNo; // Button to 'Chi Tiết Nợ' (renamed from btnXemChiTietNo for clarity/consistency)
        private System.Windows.Forms.ComboBox cboFilterLoaiDocGia; // ComboBox for filtering by reader type
        private System.Windows.Forms.ComboBox cboFilterTrangThaiThe; // ComboBox for filtering by card status
        private MaterialSkin.Controls.MaterialCheckbox chkHienThiDaXoa; // Checkbox for 'Hiển thị đã xóa'
        private MaterialSkin.Controls.MaterialTextBox2 txtTimKiem; // Search text box
        private MaterialSkin.Controls.MaterialButton btnTimKiem; // Search button
        private System.Windows.Forms.DataGridView dgvDocGia; // The main data grid view
        private System.Windows.Forms.ToolTip toolTipTimKiem; // Tooltip for search box

        // --------------------------------------------------------

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose(); // Ensure ToolTip and other components are disposed
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            // 1. Begin SuspendLayout for optimized drawing
            this.SuspendLayout();

            // 2. Initialize components (e.g., ToolTip)
            this.components = new System.ComponentModel.Container(); // Initialize components container
            this.toolTipTimKiem = new System.Windows.Forms.ToolTip(this.components); // Initialize ToolTip with components

            // 3. Create instance for all Controls
            // Panels first
            this.panelDetails = new System.Windows.Forms.Panel();
            this.panelGrid = new System.Windows.Forms.Panel();

            // Controls within panelDetails
            this.txtId = new MaterialSkin.Controls.MaterialTextBox2();
            this.txtMaDocGia = new MaterialSkin.Controls.MaterialTextBox2();
            this.txtTenDocGia = new MaterialSkin.Controls.MaterialTextBox2();
            this.txtDienThoai = new MaterialSkin.Controls.MaterialTextBox2();
            this.dtpNgaySinh = new System.Windows.Forms.DateTimePicker();
            this.txtDiaChi = new MaterialSkin.Controls.MaterialTextBox2();
            this.txtEmail = new MaterialSkin.Controls.MaterialTextBox2();
            this.cboLoaiDocGia = new System.Windows.Forms.ComboBox();
            this.txtTenDangNhap = new MaterialSkin.Controls.MaterialTextBox2();
            this.txtMatKhau = new MaterialSkin.Controls.MaterialTextBox2();
            this.dtpNgayLapThe = new System.Windows.Forms.DateTimePicker();
            this.dtpNgayHetHan = new System.Windows.Forms.DateTimePicker();
            this.txtTienNo = new MaterialSkin.Controls.MaterialTextBox2();
            this.txtSoTienThu = new MaterialSkin.Controls.MaterialTextBox2();
            this.btnThuTienPhat = new MaterialSkin.Controls.MaterialButton();
            this.btnLuu = new MaterialSkin.Controls.MaterialButton();
            this.btnBoQua = new MaterialSkin.Controls.MaterialButton();

            // Controls within panelGrid
            this.btnThem = new MaterialSkin.Controls.MaterialButton();
            this.btnSua = new MaterialSkin.Controls.MaterialButton();
            this.btnXoa = new MaterialSkin.Controls.MaterialButton();
            this.btnKhoiPhuc = new MaterialSkin.Controls.MaterialButton();
            this.btnXemLichSu = new MaterialSkin.Controls.MaterialButton();
            this.btnXemChiTietNo = new MaterialSkin.Controls.MaterialButton();
            this.cboFilterLoaiDocGia = new System.Windows.Forms.ComboBox();
            this.cboFilterTrangThaiThe = new System.Windows.Forms.ComboBox();
            this.chkHienThiDaXoa = new MaterialSkin.Controls.MaterialCheckbox();
            this.txtTimKiem = new MaterialSkin.Controls.MaterialTextBox2();
            this.btnTimKiem = new MaterialSkin.Controls.MaterialButton();
            this.dgvDocGia = new System.Windows.Forms.DataGridView();

            // 4. Configure UserControl itself (this)
            //
            // ucQuanLyDocGia
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F); // Standard scaling
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            // Add the main panels to the UserControl
            this.Controls.Add(this.panelGrid);
            this.Controls.Add(this.panelDetails); // Add panelDetails first so panelGrid can fill remaining space below it
            this.Name = "ucQuanLyDocGia";
            this.Padding = new System.Windows.Forms.Padding(10); // Add padding around the edges
            this.Size = new System.Drawing.Size(900, 600); // Example size for the user control
            // Attach Load event handler
            this.Load += new System.EventHandler(this.ucQuanLyDocGia_Load);

            // 5. Configure Panel Details and add its child Controls
            //
            // panelDetails
            //
            this.panelDetails.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle; // Optional border
            this.panelDetails.Dock = System.Windows.Forms.DockStyle.Top; // Anchor to the top
            this.panelDetails.Location = new System.Drawing.Point(10, 10); // Positioned after UserControl's padding
            this.panelDetails.Margin = new System.Windows.Forms.Padding(3, 3, 3, 10); // Add margin below the panel
            this.panelDetails.Name = "panelDetails";
            this.panelDetails.Padding = new System.Windows.Forms.Padding(10); // Padding inside the panel
            this.panelDetails.Size = new System.Drawing.Size(880, 260); // Example size for details area
            this.panelDetails.TabIndex = 0;
            // Add all child controls to panelDetails
            this.panelDetails.Controls.Add(this.btnBoQua);
            this.panelDetails.Controls.Add(this.btnLuu);
            this.panelDetails.Controls.Add(this.btnThuTienPhat); // Add payment button
            this.panelDetails.Controls.Add(this.txtSoTienThu); // Add amount input
            this.panelDetails.Controls.Add(this.txtTienNo);
            this.panelDetails.Controls.Add(this.dtpNgayHetHan);
            this.panelDetails.Controls.Add(this.dtpNgayLapThe);
            this.panelDetails.Controls.Add(this.txtMatKhau);
            this.panelDetails.Controls.Add(this.txtTenDangNhap);
            this.panelDetails.Controls.Add(this.cboLoaiDocGia);
            this.panelDetails.Controls.Add(this.txtEmail);
            this.panelDetails.Controls.Add(this.txtDiaChi);
            this.panelDetails.Controls.Add(this.dtpNgaySinh);
            this.panelDetails.Controls.Add(this.txtDienThoai);
            this.panelDetails.Controls.Add(this.txtTenDocGia);
            this.panelDetails.Controls.Add(this.txtMaDocGia);
            this.panelDetails.Controls.Add(this.txtId);
            // Ensure Controls in panelDetails are ordered by TabIndex later

            // 6. Configure Panel Grid and add its child Controls
            //
            // panelGrid
            //
            this.panelGrid.Dock = System.Windows.Forms.DockStyle.Fill; // Fill the remaining space
            this.panelGrid.Location = new System.Drawing.Point(10, 280); // Positioned below panelDetails + margin
            this.panelGrid.Name = "panelGrid";
            this.panelGrid.Padding = new System.Windows.Forms.Padding(10, 5, 10, 10); // Padding inside panelGrid
            this.panelGrid.Size = new System.Drawing.Size(880, 310); // Size is calculated by Dock.Fill
            this.panelGrid.TabIndex = 1;
            // Add all child controls to panelGrid
            this.panelGrid.Controls.Add(this.dgvDocGia); // Add DGV first so others can be placed relative to its container
            this.panelGrid.Controls.Add(this.btnTimKiem);
            this.panelGrid.Controls.Add(this.txtTimKiem);
            this.panelGrid.Controls.Add(this.chkHienThiDaXoa);
            this.panelGrid.Controls.Add(this.cboFilterTrangThaiThe);
            this.panelGrid.Controls.Add(this.cboFilterLoaiDocGia);
            this.panelGrid.Controls.Add(this.btnXemChiTietNo); // Add Debt Detail button
            this.panelGrid.Controls.Add(this.btnXemLichSu); // Add History button
            this.panelGrid.Controls.Add(this.btnKhoiPhuc);
            this.panelGrid.Controls.Add(this.btnXoa);
            this.panelGrid.Controls.Add(this.btnSua);
            this.panelGrid.Controls.Add(this.btnThem);
            // Ensure Controls in panelGrid are ordered by TabIndex later

            // 7. Configure detailed properties for each Control (arranged by visual layout)

            // --- Controls within panelDetails ---

            // Row 1
            //
            // txtId (Read-only)
            //
            this.txtId.AnimateReadOnly = true;
            this.txtId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtId.Depth = 0;
            this.txtId.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtId.HideSelection = true;
            this.txtId.Hint = "ID";
            this.txtId.LeadingIcon = null;
            this.txtId.Location = new System.Drawing.Point(15, 15); // Position in panelDetails
            this.txtId.MaxLength = 32767;
            this.txtId.MouseState = MaterialSkin.MouseState.OUT;
            this.txtId.Name = "txtId";
            this.txtId.PasswordChar = '\0';
            this.txtId.PrefixSuffixText = null;
            this.txtId.ReadOnly = true;
            this.txtId.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtId.SelectedText = "";
            this.txtId.SelectionLength = 0;
            this.txtId.SelectionStart = 0;
            this.txtId.ShortcutsEnabled = true;
            this.txtId.Size = new System.Drawing.Size(100, 48); // Material Design tall size
            this.txtId.TabIndex = 0; // TabIndex 0 for the first field
            this.txtId.TabStop = false; // Not tabbable as it's read-only
            this.txtId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtId.TrailingIcon = null;
            this.txtId.UseSystemPasswordChar = false;
            this.txtId.UseTallSize = true;

            //
            // txtMaDocGia (Read-only)
            //
            this.txtMaDocGia.AnimateReadOnly = true;
            this.txtMaDocGia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaDocGia.Depth = 0;
            this.txtMaDocGia.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtMaDocGia.HideSelection = true;
            this.txtMaDocGia.Hint = "Mã Độc Giả";
            this.txtMaDocGia.LeadingIcon = null;
            this.txtMaDocGia.Location = new System.Drawing.Point(130, 15);
            this.txtMaDocGia.MaxLength = 10; // Set max length
            this.txtMaDocGia.MouseState = MaterialSkin.MouseState.OUT;
            this.txtMaDocGia.Name = "txtMaDocGia";
            this.txtMaDocGia.PasswordChar = '\0';
            this.txtMaDocGia.PrefixSuffixText = null;
            this.txtMaDocGia.ReadOnly = true;
            this.txtMaDocGia.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtMaDocGia.SelectedText = "";
            this.txtMaDocGia.SelectionLength = 0;
            this.txtMaDocGia.SelectionStart = 0;
            this.txtMaDocGia.ShortcutsEnabled = true;
            this.txtMaDocGia.Size = new System.Drawing.Size(120, 48);
            this.txtMaDocGia.TabIndex = 1; // TabIndex 1
            this.txtMaDocGia.TabStop = false; // Not tabbable
            this.txtMaDocGia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaDocGia.TrailingIcon = null;
            this.txtMaDocGia.UseSystemPasswordChar = false;
            this.txtMaDocGia.UseTallSize = true;

            //
            // txtTenDocGia
            //
            this.txtTenDocGia.AnimateReadOnly = false;
            this.txtTenDocGia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenDocGia.Depth = 0;
            this.txtTenDocGia.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtTenDocGia.HideSelection = true;
            this.txtTenDocGia.Hint = "Tên Độc Giả";
            this.txtTenDocGia.LeadingIcon = null;
            this.txtTenDocGia.Location = new System.Drawing.Point(265, 15); // Adjusted position
            this.txtTenDocGia.MaxLength = 50;
            this.txtTenDocGia.MouseState = MaterialSkin.MouseState.OUT;
            this.txtTenDocGia.Name = "txtTenDocGia";
            this.txtTenDocGia.PasswordChar = '\0';
            this.txtTenDocGia.PrefixSuffixText = null;
            this.txtTenDocGia.ReadOnly = false;
            this.txtTenDocGia.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtTenDocGia.SelectedText = "";
            this.txtTenDocGia.SelectionLength = 0;
            this.txtTenDocGia.SelectionStart = 0;
            this.txtTenDocGia.ShortcutsEnabled = true;
            this.txtTenDocGia.Size = new System.Drawing.Size(300, 48); // Adjusted size
            this.txtTenDocGia.TabIndex = 2; // TabIndex 2
            this.txtTenDocGia.TabStop = true;
            this.txtTenDocGia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenDocGia.TrailingIcon = null;
            this.txtTenDocGia.UseSystemPasswordChar = false;
            this.txtTenDocGia.UseTallSize = true;

            //
            // txtDienThoai
            //
            this.txtDienThoai.AnimateReadOnly = false;
            this.txtDienThoai.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDienThoai.Depth = 0;
            this.txtDienThoai.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtDienThoai.HideSelection = true;
            this.txtDienThoai.Hint = "Điện thoại";
            this.txtDienThoai.LeadingIcon = null;
            this.txtDienThoai.Location = new System.Drawing.Point(580, 15); // Positioned next to TenDocGia
            this.txtDienThoai.MaxLength = 15;
            this.txtDienThoai.MouseState = MaterialSkin.MouseState.OUT;
            this.txtDienThoai.Name = "txtDienThoai";
            this.txtDienThoai.PasswordChar = '\0';
            this.txtDienThoai.PrefixSuffixText = null;
            this.txtDienThoai.ReadOnly = false;
            this.txtDienThoai.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtDienThoai.SelectedText = "";
            this.txtDienThoai.SelectionLength = 0;
            this.txtDienThoai.SelectionStart = 0;
            this.txtDienThoai.ShortcutsEnabled = true;
            this.txtDienThoai.Size = new System.Drawing.Size(270, 48); // Adjusted size
            this.txtDienThoai.TabIndex = 3; // TabIndex 3
            this.txtDienThoai.TabStop = true;
            this.txtDienThoai.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDienThoai.TrailingIcon = null;
            this.txtDienThoai.UseSystemPasswordChar = false;
            this.txtDienThoai.UseTallSize = true;

            // Row 2
            //
            // dtpNgaySinh
            //
            this.dtpNgaySinh.CustomFormat = "dd/MM/yyyy";
            this.dtpNgaySinh.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))); // Adjusted Font
            this.dtpNgaySinh.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpNgaySinh.Location = new System.Drawing.Point(15, 85); // Positioned below txtId/txtMaDocGia
            this.dtpNgaySinh.Name = "dtpNgaySinh";
            this.dtpNgaySinh.Size = new System.Drawing.Size(160, 28); // Adjusted size
            this.dtpNgaySinh.TabIndex = 4; // TabIndex 4

            //
            // txtDiaChi
            //
            this.txtDiaChi.AnimateReadOnly = false;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Depth = 0;
            this.txtDiaChi.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.Hint = "Địa Chỉ";
            this.txtDiaChi.LeadingIcon = null;
            this.txtDiaChi.Location = new System.Drawing.Point(190, 75); // Positioned next to dtpNgaySinh
            this.txtDiaChi.MaxLength = 100;
            this.txtDiaChi.MouseState = MaterialSkin.MouseState.OUT;
            this.txtDiaChi.Name = "txtDiaChi";
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PrefixSuffixText = null;
            this.txtDiaChi.ReadOnly = false;
            this.txtDiaChi.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(385, 48); // Adjusted size
            this.txtDiaChi.TabIndex = 5; // TabIndex 5
            this.txtDiaChi.TabStop = true;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TrailingIcon = null;
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.UseTallSize = true;

            //
            // txtEmail
            //
            this.txtEmail.AnimateReadOnly = false;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Depth = 0;
            this.txtEmail.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtEmail.HideSelection = true;
            this.txtEmail.Hint = "Email";
            this.txtEmail.LeadingIcon = null;
            this.txtEmail.Location = new System.Drawing.Point(590, 75); // Positioned next to txtDiaChi
            this.txtEmail.MaxLength = 50;
            this.txtEmail.MouseState = MaterialSkin.MouseState.OUT;
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PrefixSuffixText = null;
            this.txtEmail.ReadOnly = false;
            this.txtEmail.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(260, 48); // Adjusted size
            this.txtEmail.TabIndex = 6; // TabIndex 6
            this.txtEmail.TabStop = true;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TrailingIcon = null;
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.UseTallSize = true;

            // Row 3
            //
            // cboLoaiDocGia
            //
            this.cboLoaiDocGia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.cboLoaiDocGia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.cboLoaiDocGia.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLoaiDocGia.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))); // Adjusted Font
            this.cboLoaiDocGia.FormattingEnabled = true;
            this.cboLoaiDocGia.Location = new System.Drawing.Point(15, 145); // Positioned below Ngày Sinh
            this.cboLoaiDocGia.Name = "cboLoaiDocGia";
            this.cboLoaiDocGia.Size = new System.Drawing.Size(260, 30); // Adjusted size
            this.cboLoaiDocGia.TabIndex = 7; // TabIndex 7

            //
            // txtTenDangNhap
            //
            this.txtTenDangNhap.AnimateReadOnly = false;
            this.txtTenDangNhap.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenDangNhap.Depth = 0;
            this.txtTenDangNhap.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtTenDangNhap.HideSelection = true;
            this.txtTenDangNhap.Hint = "Tên đăng nhập";
            this.txtTenDangNhap.LeadingIcon = null;
            this.txtTenDangNhap.Location = new System.Drawing.Point(290, 135); // Positioned next to cboLoaiDocGia
            this.txtTenDangNhap.MaxLength = 50;
            this.txtTenDangNhap.MouseState = MaterialSkin.MouseState.OUT;
            this.txtTenDangNhap.Name = "txtTenDangNhap";
            this.txtTenDangNhap.PasswordChar = '\0';
            this.txtTenDangNhap.PrefixSuffixText = null;
            this.txtTenDangNhap.ReadOnly = false;
            this.txtTenDangNhap.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtTenDangNhap.SelectedText = "";
            this.txtTenDangNhap.SelectionLength = 0;
            this.txtTenDangNhap.SelectionStart = 0;
            this.txtTenDangNhap.ShortcutsEnabled = true;
            this.txtTenDangNhap.Size = new System.Drawing.Size(285, 48); // Adjusted size
            this.txtTenDangNhap.TabIndex = 8; // TabIndex 8
            this.txtTenDangNhap.TabStop = true;
            this.txtTenDangNhap.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenDangNhap.TrailingIcon = null;
            this.txtTenDangNhap.UseSystemPasswordChar = false;
            this.txtTenDangNhap.UseTallSize = true;

            //
            // txtMatKhau
            //
            this.txtMatKhau.AnimateReadOnly = false;
            this.txtMatKhau.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMatKhau.Depth = 0;
            this.txtMatKhau.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtMatKhau.HideSelection = true;
            this.txtMatKhau.Hint = "Mật khẩu";
            this.txtMatKhau.LeadingIcon = null;
            this.txtMatKhau.Location = new System.Drawing.Point(590, 135); // Positioned next to txtTenDangNhap
            this.txtMatKhau.MaxLength = 50;
            this.txtMatKhau.MouseState = MaterialSkin.MouseState.OUT;
            this.txtMatKhau.Name = "txtMatKhau";
            this.txtMatKhau.PasswordChar = '●'; // Use bullet character
            this.txtMatKhau.PrefixSuffixText = null;
            this.txtMatKhau.ReadOnly = false;
            this.txtMatKhau.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtMatKhau.SelectedText = "";
            this.txtMatKhau.SelectionLength = 0;
            this.txtMatKhau.SelectionStart = 0;
            this.txtMatKhau.ShortcutsEnabled = true;
            this.txtMatKhau.Size = new System.Drawing.Size(260, 48); // Adjusted size
            this.txtMatKhau.TabIndex = 9; // TabIndex 9
            this.txtMatKhau.TabStop = true;
            this.txtMatKhau.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMatKhau.TrailingIcon = null; // Could add visibility toggle icon
            this.txtMatKhau.UseSystemPasswordChar = true; // Use system password char behavior
            this.txtMatKhau.UseTallSize = true;

            // Row 4
            //
            // dtpNgayLapThe
            //
            this.dtpNgayLapThe.CustomFormat = "dd/MM/yyyy";
            this.dtpNgayLapThe.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))); // Adjusted Font
            this.dtpNgayLapThe.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpNgayLapThe.Location = new System.Drawing.Point(15, 205); // Positioned below cboLoaiDocGia
            this.dtpNgayLapThe.Name = "dtpNgayLapThe";
            this.dtpNgayLapThe.Size = new System.Drawing.Size(140, 28); // Adjusted size
            this.dtpNgayLapThe.TabIndex = 10; // TabIndex 10

            //
            // dtpNgayHetHan
            //
            this.dtpNgayHetHan.CustomFormat = "dd/MM/yyyy";
            this.dtpNgayHetHan.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))); // Adjusted Font
            this.dtpNgayHetHan.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpNgayHetHan.Location = new System.Drawing.Point(175, 205); // Positioned next to dtpNgayLapThe
            this.dtpNgayHetHan.Name = "dtpNgayHetHan";
            this.dtpNgayHetHan.Size = new System.Drawing.Size(160, 28); // Adjusted size
            this.dtpNgayHetHan.TabIndex = 11; // TabIndex 11

            //
            // txtTienNo (Read-only)
            //
            this.txtTienNo.AnimateReadOnly = true;
            this.txtTienNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTienNo.Depth = 0;
            this.txtTienNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtTienNo.HideSelection = true;
            this.txtTienNo.Hint = "Tiền Nợ";
            this.txtTienNo.LeadingIcon = null;
            this.txtTienNo.Location = new System.Drawing.Point(350, 195); // Positioned next to DatePickers
            this.txtTienNo.MaxLength = 32767;
            this.txtTienNo.MouseState = MaterialSkin.MouseState.OUT;
            this.txtTienNo.Name = "txtTienNo";
            this.txtTienNo.PasswordChar = '\0';
            this.txtTienNo.PrefixSuffixText = "VNĐ"; // Add currency unit
            this.txtTienNo.ReadOnly = true;
            this.txtTienNo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtTienNo.SelectedText = "";
            this.txtTienNo.SelectionLength = 0;
            this.txtTienNo.SelectionStart = 0;
            this.txtTienNo.ShortcutsEnabled = true;
            this.txtTienNo.Size = new System.Drawing.Size(120, 48); // Adjusted size
            this.txtTienNo.TabIndex = 12; // TabIndex 12
            this.txtTienNo.TabStop = false; // Not tabbable
            this.txtTienNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Right; // Align right for currency
            this.txtTienNo.TrailingIcon = null;
            this.txtTienNo.UseSystemPasswordChar = false;
            this.txtTienNo.UseTallSize = true;

            //
            // txtSoTienThu (Input for payment)
            //
            this.txtSoTienThu.AnimateReadOnly = false;
            this.txtSoTienThu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoTienThu.Depth = 0;
            this.txtSoTienThu.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtSoTienThu.HideSelection = true;
            this.txtSoTienThu.Hint = "Số tiền thu";
            this.txtSoTienThu.LeadingIcon = null;
            this.txtSoTienThu.Location = new System.Drawing.Point(480, 195); // Positioned next to txtTienNo
            this.txtSoTienThu.MaxLength = 15; // Appropriate max length for currency
            this.txtSoTienThu.MouseState = MaterialSkin.MouseState.OUT;
            this.txtSoTienThu.Name = "txtSoTienThu";
            this.txtSoTienThu.PasswordChar = '\0';
            this.txtSoTienThu.PrefixSuffixText = "VNĐ"; // Add currency unit
            this.txtSoTienThu.ReadOnly = false;
            this.txtSoTienThu.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtSoTienThu.SelectedText = "";
            this.txtSoTienThu.SelectionLength = 0;
            this.txtSoTienThu.SelectionStart = 0;
            this.txtSoTienThu.ShortcutsEnabled = true;
            this.txtSoTienThu.Size = new System.Drawing.Size(120, 48); // Adjusted size
            this.txtSoTienThu.TabIndex = 13; // TabIndex 13
            this.txtSoTienThu.TabStop = true;
            this.txtSoTienThu.TextAlign = System.Windows.Forms.HorizontalAlignment.Right; // Align right for currency
            this.txtSoTienThu.TrailingIcon = null;
            this.txtSoTienThu.UseSystemPasswordChar = false;
            this.txtSoTienThu.UseTallSize = true;
            this.txtSoTienThu.Enabled = false; // Initially disabled

            //
            // btnThuTienPhat
            //
            this.btnThuTienPhat.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnThuTienPhat.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnThuTienPhat.Depth = 0;
            this.btnThuTienPhat.HighEmphasis = true;
            this.btnThuTienPhat.Icon = null;
            this.btnThuTienPhat.Location = new System.Drawing.Point(610, 201); // Positioned next to txtSoTienThu
            this.btnThuTienPhat.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnThuTienPhat.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnThuTienPhat.Name = "btnThuTienPhat";
            this.btnThuTienPhat.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnThuTienPhat.Size = new System.Drawing.Size(96, 36); // Adjusted size
            this.btnThuTienPhat.TabIndex = 14; // TabIndex 14
            this.btnThuTienPhat.Text = "Thu Phạt";
            this.btnThuTienPhat.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
            this.btnThuTienPhat.UseAccentColor = true; // Use accent color for prominent action
            this.btnThuTienPhat.UseVisualStyleBackColor = true;
            this.btnThuTienPhat.Enabled = false; // Initially disabled
            // Attach Click event
            this.btnThuTienPhat.Click += new System.EventHandler(this.btnThuTienPhat_Click);


            // Row 4 (Buttons on the right)
            //
            // btnLuu
            //
            this.btnLuu.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnLuu.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnLuu.Depth = 0;
            this.btnLuu.HighEmphasis = true;
            this.btnLuu.Icon = null;
            this.btnLuu.Location = new System.Drawing.Point(710, 201); // Positioned right of Thu Phạt
            this.btnLuu.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnLuu.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnLuu.Name = "btnLuu";
            this.btnLuu.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnLuu.Size = new System.Drawing.Size(70, 36); // Adjusted size
            this.btnLuu.TabIndex = 15; // TabIndex 15
            this.btnLuu.Text = "Lưu";
            this.btnLuu.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
            this.btnLuu.UseAccentColor = true; // Use accent color for Save
            this.btnLuu.UseVisualStyleBackColor = true;
            // Attach Click event
            this.btnLuu.Click += new System.EventHandler(this.btnLuu_Click);


            //
            // btnBoQua
            //
            this.btnBoQua.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnBoQua.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnBoQua.Depth = 0;
            this.btnBoQua.HighEmphasis = false;
            this.btnBoQua.Icon = null;
            this.btnBoQua.Location = new System.Drawing.Point(785, 201); // Positioned right of btnLuu
            this.btnBoQua.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnBoQua.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnBoQua.Name = "btnBoQua";
            this.btnBoQua.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnBoQua.Size = new System.Drawing.Size(75, 36); // Adjusted size
            this.btnBoQua.TabIndex = 16; // TabIndex 16
            this.btnBoQua.Text = "Bỏ qua";
            this.btnBoQua.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
            this.btnBoQua.UseAccentColor = false;
            this.btnBoQua.UseVisualStyleBackColor = true;
            // Attach Click event
            this.btnBoQua.Click += new System.EventHandler(this.btnBoQua_Click);

            // --- Controls within panelGrid ---

            // Action Buttons (Top left)
            //
            // btnThem
            //
            this.btnThem.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnThem.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnThem.Depth = 0;
            this.btnThem.HighEmphasis = true; // Highlight Add button
            this.btnThem.Icon = null;
            this.btnThem.Location = new System.Drawing.Point(15, 10); // Position in panelGrid
            this.btnThem.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnThem.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnThem.Name = "btnThem";
            this.btnThem.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnThem.Size = new System.Drawing.Size(80, 36); // Adjusted size
            this.btnThem.TabIndex = 0; // TabIndex 0 within panelGrid controls
            this.btnThem.Text = "Thêm";
            this.btnThem.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
            this.btnThem.UseAccentColor = false;
            this.btnThem.UseVisualStyleBackColor = true;
            // Attach Click event
            this.btnThem.Click += new System.EventHandler(this.btnThem_Click);

            //
            // btnSua
            //
            this.btnSua.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnSua.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnSua.Depth = 0;
            this.btnSua.HighEmphasis = false;
            this.btnSua.Icon = null;
            this.btnSua.Location = new System.Drawing.Point(100, 10); // Positioned next to btnThem
            this.btnSua.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnSua.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnSua.Name = "btnSua";
            this.btnSua.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnSua.Size = new System.Drawing.Size(70, 36); // Adjusted size
            this.btnSua.TabIndex = 1; // TabIndex 1
            this.btnSua.Text = "Sửa";
            this.btnSua.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
            this.btnSua.UseAccentColor = false;
            this.btnSua.UseVisualStyleBackColor = true;
            // Attach Click event
            this.btnSua.Click += new System.EventHandler(this.btnSua_Click);

            //
            // btnXoa
            //
            this.btnXoa.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnXoa.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnXoa.Depth = 0;
            this.btnXoa.HighEmphasis = false;
            this.btnXoa.Icon = null;
            this.btnXoa.Location = new System.Drawing.Point(175, 10); // Positioned next to btnSua
            this.btnXoa.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnXoa.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnXoa.Name = "btnXoa";
            this.btnXoa.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnXoa.Size = new System.Drawing.Size(70, 36); // Adjusted size
            this.btnXoa.TabIndex = 2; // TabIndex 2
            this.btnXoa.Text = "Xóa";
            this.btnXoa.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
            this.btnXoa.UseAccentColor = true; // Use accent color for delete
            this.btnXoa.UseVisualStyleBackColor = true;
            // Attach Click event
            this.btnXoa.Click += new System.EventHandler(this.btnXoa_Click);

            //
            // btnKhoiPhuc
            //
            this.btnKhoiPhuc.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnKhoiPhuc.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnKhoiPhuc.Depth = 0;
            this.btnKhoiPhuc.HighEmphasis = false;
            this.btnKhoiPhuc.Icon = null;
            this.btnKhoiPhuc.Location = new System.Drawing.Point(250, 10); // Positioned next to btnXoa
            this.btnKhoiPhuc.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnKhoiPhuc.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnKhoiPhuc.Name = "btnKhoiPhuc";
            this.btnKhoiPhuc.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnKhoiPhuc.Size = new System.Drawing.Size(96, 36); // Adjusted size
            this.btnKhoiPhuc.TabIndex = 3; // TabIndex 3
            this.btnKhoiPhuc.Text = "Phục hồi";
            this.btnKhoiPhuc.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
            this.btnKhoiPhuc.UseAccentColor = false;
            this.btnKhoiPhuc.UseVisualStyleBackColor = true;
            // Attach Click event
            this.btnKhoiPhuc.Click += new System.EventHandler(this.btnKhoiPhuc_Click);

            //
            // btnXemLichSu
            //
            this.btnXemLichSu.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnXemLichSu.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnXemLichSu.Depth = 0;
            this.btnXemLichSu.HighEmphasis = false;
            this.btnXemLichSu.Icon = null;
            this.btnXemLichSu.Location = new System.Drawing.Point(350, 10); // Positioned next to btnKhoiPhuc
            this.btnXemLichSu.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnXemLichSu.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnXemLichSu.Name = "btnXemLichSu";
            this.btnXemLichSu.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnXemLichSu.Size = new System.Drawing.Size(124, 36); // Adjusted size
            this.btnXemLichSu.TabIndex = 4; // TabIndex 4
            this.btnXemLichSu.Text = "XEM LỊCH SỬ";
            this.btnXemLichSu.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
            this.btnXemLichSu.UseAccentColor = false;
            this.btnXemLichSu.UseVisualStyleBackColor = true;
            this.btnXemLichSu.Enabled = false; // Initially disabled
                                               // Attach Click event
            this.btnXemLichSu.Click += new System.EventHandler(this.btnXemLichSu_Click);

            //
            // btnChiTietNo
            //
            this.btnXemChiTietNo.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnXemChiTietNo.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnXemChiTietNo.Depth = 0;
            this.btnXemChiTietNo.HighEmphasis = false;
            this.btnXemChiTietNo.Icon = null;
            this.btnXemChiTietNo.Location = new System.Drawing.Point(480, 10); // Positioned next to btnXemLichSu
            this.btnXemChiTietNo.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnXemChiTietNo.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnXemChiTietNo.Name = "btnChiTietNo";
            this.btnXemChiTietNo.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnXemChiTietNo.Size = new System.Drawing.Size(114, 36); // Adjusted size
            this.btnXemChiTietNo.TabIndex = 5; // TabIndex 5
            this.btnXemChiTietNo.Text = "Chi Tiết Nợ";
            this.btnXemChiTietNo.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Outlined;
            this.btnXemChiTietNo.UseAccentColor = false;
            this.btnXemChiTietNo.UseVisualStyleBackColor = true;
            this.btnXemChiTietNo.Enabled = false; // Initially disabled
                                                  // Attach Click event
            this.btnXemChiTietNo.Click += new System.EventHandler(this.btnXemChiTietNo_Click);

            // Filter Controls (Below action buttons, left aligned)
            //
            // cboFilterLoaiDocGia
            //
            this.cboFilterLoaiDocGia.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboFilterLoaiDocGia.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))); // Adjusted Font
            this.cboFilterLoaiDocGia.FormattingEnabled = true;
            this.cboFilterLoaiDocGia.Location = new System.Drawing.Point(15, 55); // Positioned below action buttons
            this.cboFilterLoaiDocGia.Name = "cboFilterLoaiDocGia";
            this.cboFilterLoaiDocGia.Size = new System.Drawing.Size(200, 26); // Adjusted size
            this.cboFilterLoaiDocGia.TabIndex = 6; // TabIndex 6

            //
            // cboFilterTrangThaiThe
            //
            this.cboFilterTrangThaiThe.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboFilterTrangThaiThe.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))); // Adjusted Font
            this.cboFilterTrangThaiThe.FormattingEnabled = true;
            this.cboFilterTrangThaiThe.Location = new System.Drawing.Point(220, 55); // Positioned next to cboFilterLoaiDocGia
            this.cboFilterTrangThaiThe.Name = "cboFilterTrangThaiThe";
            this.cboFilterTrangThaiThe.Size = new System.Drawing.Size(180, 26); // Adjusted size
            this.cboFilterTrangThaiThe.TabIndex = 7; // TabIndex 7

            //
            // chkHienThiDaXoa
            //
            this.chkHienThiDaXoa.AutoSize = true;
            this.chkHienThiDaXoa.Depth = 0;
            this.chkHienThiDaXoa.Location = new System.Drawing.Point(405, 50); // Positioned next to filter ComboBoxes
            this.chkHienThiDaXoa.Margin = new System.Windows.Forms.Padding(0);
            this.chkHienThiDaXoa.MouseLocation = new System.Drawing.Point(-1, -1);
            this.chkHienThiDaXoa.MouseState = MaterialSkin.MouseState.HOVER;
            this.chkHienThiDaXoa.Name = "chkHienThiDaXoa";
            this.chkHienThiDaXoa.ReadOnly = false;
            this.chkHienThiDaXoa.Ripple = true;
            this.chkHienThiDaXoa.Size = new System.Drawing.Size(142, 37); // Adjusted size for MaterialSkin checkbox
            this.chkHienThiDaXoa.TabIndex = 8; // TabIndex 8
            this.chkHienThiDaXoa.Text = "Hiển thị đã xóa";
            this.chkHienThiDaXoa.UseVisualStyleBackColor = true;
            // Attach CheckedChanged event
            this.chkHienThiDaXoa.CheckedChanged += new System.EventHandler(this.chkHienThiDaXoa_CheckedChanged);

            // Search Controls (Top right)
            //
            // txtTimKiem
            //
            this.txtTimKiem.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); // Anchor to top and right
            this.txtTimKiem.AnimateReadOnly = false;
            this.txtTimKiem.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTimKiem.Depth = 0;
            this.txtTimKiem.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.txtTimKiem.HideSelection = true;
            this.txtTimKiem.Hint = "Nhập tên, mã, email...";
            this.txtTimKiem.LeadingIcon = null;
            this.txtTimKiem.Location = new System.Drawing.Point(600, 10); // Positioned on the right
            this.txtTimKiem.MaxLength = 100;
            this.txtTimKiem.MouseState = MaterialSkin.MouseState.OUT;
            this.txtTimKiem.Name = "txtTimKiem";
            this.txtTimKiem.PasswordChar = '\0';
            this.txtTimKiem.PrefixSuffixText = null;
            this.txtTimKiem.ReadOnly = false;
            this.txtTimKiem.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtTimKiem.SelectedText = "";
            this.txtTimKiem.SelectionLength = 0;
            this.txtTimKiem.SelectionStart = 0;
            this.txtTimKiem.ShortcutsEnabled = true;
            this.txtTimKiem.Size = new System.Drawing.Size(180, 48); // Adjusted size
            this.txtTimKiem.TabIndex = 9; // TabIndex 9
            this.txtTimKiem.TabStop = true;
            this.txtTimKiem.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.toolTipTimKiem.SetToolTip(this.txtTimKiem, "Nhập tên, mã độc giả hoặc email để tìm kiếm. Nhấn Enter hoặc nút Tìm."); // Add ToolTip
            this.txtTimKiem.TrailingIcon = null;
            this.txtTimKiem.UseSystemPasswordChar = false;
            this.txtTimKiem.UseTallSize = true;
            // Attach KeyDown event for Enter key
            this.txtTimKiem.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtTimKiem_KeyDown);


            //
            // btnTimKiem
            //
            this.btnTimKiem.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); // Anchor to top and right
            this.btnTimKiem.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnTimKiem.Density = MaterialSkin.Controls.MaterialButton.MaterialButtonDensity.Default;
            this.btnTimKiem.Depth = 0;
            this.btnTimKiem.HighEmphasis = true;
            this.btnTimKiem.Icon = null;
            this.btnTimKiem.Location = new System.Drawing.Point(785, 16); // Positioned next to txtTimKiem
            this.btnTimKiem.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnTimKiem.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnTimKiem.Name = "btnTimKiem";
            this.btnTimKiem.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnTimKiem.Size = new System.Drawing.Size(70, 36); // Adjusted size
            this.btnTimKiem.TabIndex = 10; // TabIndex 10
            this.btnTimKiem.Text = "Tìm";
            this.btnTimKiem.Type = MaterialSkin.Controls.MaterialButton.MaterialButtonType.Contained;
            this.btnTimKiem.UseAccentColor = false;
            this.btnTimKiem.UseVisualStyleBackColor = true;
            // Attach Click event
            this.btnTimKiem.Click += new System.EventHandler(this.btnTimKiem_Click);

            // Data Grid View (Fills remaining space)
            //
            // dgvDocGia
            //
            this.dgvDocGia.AllowUserToAddRows = false; // Prevent adding rows directly in the grid
            this.dgvDocGia.AllowUserToDeleteRows = false; // Prevent deleting rows directly in the grid
            this.dgvDocGia.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right))); // Anchor to all sides to fill space
            this.dgvDocGia.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize; // Let it size headers
            this.dgvDocGia.Location = new System.Drawing.Point(15, 90); // Positioned below the filter controls and search box
            this.dgvDocGia.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3); // Add some space above the grid
            this.dgvDocGia.MultiSelect = false; // Allow only single row selection
            this.dgvDocGia.Name = "dgvDocGia";
            this.dgvDocGia.ReadOnly = true; // Make grid read-only; editing happens in details
            this.dgvDocGia.RowHeadersWidth = 51; // Default row header width
            this.dgvDocGia.RowTemplate.Height = 28; // Can adjust row height if needed
            this.dgvDocGia.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; // Select entire row
            this.dgvDocGia.Size = new System.Drawing.Size(850, 200); // Example size, will be resized by Anchor
            this.dgvDocGia.TabIndex = 11; // TabIndex 11
            // Attach SelectionChanged and DoubleClick events
            this.dgvDocGia.SelectionChanged += new System.EventHandler(this.dgvDocGia_SelectionChanged);
            this.dgvDocGia.DoubleClick += new System.EventHandler(this.dgvDocGia_DoubleClick);


            // 8. Finalize DataGridView configuration
            ((System.ComponentModel.ISupportInitialize)(this.dgvDocGia)).EndInit();

            // 9. End SuspendLayout and apply layout
            // Resume layout for panels before the main UserControl
            this.panelDetails.ResumeLayout(false);
            this.panelDetails.PerformLayout(); // Ensure autolayout works within panelDetails
            this.panelGrid.ResumeLayout(false);
            this.panelGrid.PerformLayout(); // Ensure autolayout works within panelGrid

            this.ResumeLayout(false); // End SuspendLayout for the main UserControl
        }

        #endregion
    }
}