// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(QLTVContext))]
    [Migration("20250424192556_SyncDatabaseSchemaAfterAddingDaAn")]
    partial class SyncDatabaseSchemaAfterAddingDaAn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CtTacgia", b =>
                {
                    b.Property<int>("IdTacGia")
                        .HasColumnType("int")
                        .HasColumnName("idTacGia");

                    b.Property<int>("IdTuaSach")
                        .HasColumnType("int")
                        .HasColumnName("idTuaSach");

                    b.HasKey("IdTacGia", "IdTuaSach")
                        .HasName("PK__CT_TACGI__0CEEA1FCD0051CCE");

                    b.HasIndex("IdTuaSach");

                    b.ToTable("CT_TACGIA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Bcluotmuontheotheloai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaBaoCao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasComputedColumnSql("(CONVERT([char](10),('BCLM'+right('0'+CONVERT([char](2),[THANG]),(2)))+CONVERT([char](4),[NAM])))", true)
                        .IsFixedLength();

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("TongSoLuotMuon")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BCLUOTMU__3213E83FE24D00BC");

                    b.ToTable("BCLUOTMUONTHEOTHELOAI", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Bcsachtratre", b =>
                {
                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCuonSach")
                        .HasColumnType("int")
                        .HasColumnName("idCuonSach");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime");

                    b.Property<int>("SoNgayTre")
                        .HasColumnType("int");

                    b.HasKey("Ngay", "IdCuonSach")
                        .HasName("PK__BCSACHTR__8F93DB29A175628C");

                    b.HasIndex("IdCuonSach");

                    b.ToTable("BCSACHTRATRE", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Chucnang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaChucNang")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasComputedColumnSql("(CONVERT([char](5),'CN'+right('000'+CONVERT([varchar](3),[id]),(3))))", true)
                        .IsFixedLength();

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenManHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__CHUCNANG__3213E83F74C8BD9B");

                    b.ToTable("CHUCNANG", (string)null);
                });

            modelBuilder.Entity("DAL.Models.CtBcluotmuontheotheloai", b =>
                {
                    b.Property<int>("IdBaoCao")
                        .HasColumnType("int")
                        .HasColumnName("idBaoCao");

                    b.Property<int>("IdTheLoai")
                        .HasColumnType("int")
                        .HasColumnName("idTheLoai");

                    b.Property<int>("SoLuotMuon")
                        .HasColumnType("int");

                    b.Property<decimal?>("TiLe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(4, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("IdBaoCao", "IdTheLoai")
                        .HasName("PK__CT_BCLUO__816BEA6EF937F0E9");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("CT_BCLUOTMUONTHEOTHELOAI", (string)null);
                });

            modelBuilder.Entity("DAL.Models.CtPhieunhap", b =>
                {
                    b.Property<int>("SoPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("IdSach")
                        .HasColumnType("int")
                        .HasColumnName("idSach");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("SoPhieuNhap", "IdSach")
                        .HasName("PK__CT_PHIEU__56D67F6A105DEA68");

                    b.HasIndex("IdSach");

                    b.ToTable("CT_PHIEUNHAP", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Cuonsach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaAn")
                        .HasColumnType("int");

                    b.Property<int>("IdSach")
                        .HasColumnType("int")
                        .HasColumnName("idSach");

                    b.Property<string>("MaCuonSach")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'CS'+right('0000'+CONVERT([varchar](10),[id]),(4))))", true)
                        .IsFixedLength();

                    b.Property<int>("TinhTrang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__CUONSACH__3213E83F6D89F2A8");

                    b.HasIndex("IdSach");

                    b.ToTable("CUONSACH", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Docgia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaAn")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("IdLoaiDocGia")
                        .HasColumnType("int")
                        .HasColumnName("idLoaiDocGia");

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("idNguoiDung");

                    b.Property<string>("MaDocGia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'DG'+right('0000'+CONVERT([varchar](10),[ID]),(4))))", true)
                        .IsFixedLength();

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayLapThe")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("TenDocGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongNoHienTai")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DOCGIA__3214EC2746716D3A");

                    b.HasIndex("IdLoaiDocGia");

                    b.HasIndex(new[] { "IdNguoiDung" }, "UQ__DOCGIA__BE010FC8379F3B32")
                        .IsUnique();

                    b.ToTable("DOCGIA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Loaidocgia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLoaiDocGia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'LDG'+right('000'+CONVERT([varchar](10),[ID]),(3))))", true)
                        .IsFixedLength();

                    b.Property<string>("TenLoaiDocGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__LOAIDOCG__3213E83F12628C52");

                    b.ToTable("LOAIDOCGIA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Nguoidung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaAn")
                        .HasColumnType("bit");

                    b.Property<int>("IdNhomNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("idNhomNguoiDung");

                    b.Property<string>("MaNguoiDung")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'ND'+right('000000'+CONVERT([varchar](4),[id]),(4))))", true)
                        .IsFixedLength();

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__NGUOIDUN__3213E83F18F0E3C1");

                    b.HasIndex("IdNhomNguoiDung");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NGUOIDUN__55F68FC041F20D99")
                        .IsUnique();

                    b.ToTable("NGUOIDUNG", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Nhomnguoidung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaNhomNguoiDung")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'NND'+right('000'+CONVERT([varchar](5),[id]),(3))))", true)
                        .IsFixedLength();

                    b.Property<string>("TenNhomNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__NHOMNGUO__3213E83FC12C1FAC");

                    b.ToTable("NHOMNGUOIDUNG", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Phieumuontra", b =>
                {
                    b.Property<int>("SoPhieuMuonTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoPhieuMuonTra"));

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCuonSach")
                        .HasColumnType("int")
                        .HasColumnName("idCuonSach");

                    b.Property<int>("IdDocGia")
                        .HasColumnType("int")
                        .HasColumnName("idDocGia");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoTienPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("SoPhieuMuonTra")
                        .HasName("PK__PHIEUMUO__EF67FB6FFDC215AB");

                    b.HasIndex("IdCuonSach");

                    b.HasIndex("IdDocGia");

                    b.ToTable("PHIEUMUONTRA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Phieunhapsach", b =>
                {
                    b.Property<int>("SoPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoPhieuNhap"));

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("SoPhieuNhap")
                        .HasName("PK__PHIEUNHA__4A9C88C19B86535C");

                    b.ToTable("PHIEUNHAPSACH", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Phieuthu", b =>
                {
                    b.Property<int>("SoPhieuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoPhieuThu"));

                    b.Property<int>("IdDocGia")
                        .HasColumnType("int")
                        .HasColumnName("idDocGia");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime");

                    b.Property<int>("SoTienThu")
                        .HasColumnType("int");

                    b.HasKey("SoPhieuThu")
                        .HasName("PK__PHIEUTHU__6D06AEAB0DEA2A8C");

                    b.HasIndex("IdDocGia");

                    b.ToTable("PHIEUTHU", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Sach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaAn")
                        .HasColumnType("int");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("IdTuaSach")
                        .HasColumnType("int")
                        .HasColumnName("idTuaSach");

                    b.Property<string>("MaSach")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'S'+right('00000'+CONVERT([varchar](10),[id]),(5))))", true)
                        .IsFixedLength();

                    b.Property<int>("NamXb")
                        .HasColumnType("int")
                        .HasColumnName("NamXB");

                    b.Property<string>("NhaXb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhaXB");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongConLai")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SACH__3213E83FE96316AC");

                    b.HasIndex("IdTuaSach");

                    b.ToTable("SACH", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Tacgia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Matacgia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasColumnName("MATACGIA")
                        .HasComputedColumnSql("(CONVERT([char](6),'TG'+right('0000'+CONVERT([varchar](10),[ID]),(4))))", true)
                        .IsFixedLength();

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__TACGIA__3213E83F564979BD");

                    b.ToTable("TACGIA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Thamso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdQdkttienThu")
                        .HasColumnType("int")
                        .HasColumnName("AD_QDKTTienThu");

                    b.Property<int>("DonGiaPhat")
                        .HasColumnType("int");

                    b.Property<int>("KhoangCachXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayMuonToiDa")
                        .HasColumnType("int");

                    b.Property<int>("SoSachMuonToiDa")
                        .HasColumnType("int");

                    b.Property<int>("ThoiHanThe")
                        .HasColumnType("int");

                    b.Property<int>("TuoiToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TuoiToiThieu")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__THAMSO__3213E83FC911CB09");

                    b.ToTable("THAMSO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Theloai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaTheLoai")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'TL'+right('0000'+CONVERT([varchar](4),[id]),(4))))", true)
                        .IsFixedLength();

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__THELOAI__3213E83F8E3B1459");

                    b.ToTable("THELOAI", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Tuasach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DaAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IdTheLoai")
                        .HasColumnType("int")
                        .HasColumnName("idTheLoai");

                    b.Property<string>("MaTuaSach")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasComputedColumnSql("(CONVERT([char](6),'TS'+right('0000'+CONVERT([varchar](10),[ID]),(4))))", true)
                        .IsFixedLength();

                    b.Property<string>("TenTuaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__TUASACH__3213E83FD0D840EA");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("TUASACH", (string)null);
                });

            modelBuilder.Entity("Phanquyen", b =>
                {
                    b.Property<int>("IdNhomNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("idNhomNguoiDung");

                    b.Property<int>("IdChucNang")
                        .HasColumnType("int")
                        .HasColumnName("idChucNang");

                    b.HasKey("IdNhomNguoiDung", "IdChucNang")
                        .HasName("PK__PHANQUYE__421733D85D0AA18B");

                    b.HasIndex("IdChucNang");

                    b.ToTable("PHANQUYEN", (string)null);
                });

            modelBuilder.Entity("CtTacgia", b =>
                {
                    b.HasOne("DAL.Models.Tacgia", null)
                        .WithMany()
                        .HasForeignKey("IdTacGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CT_TACGIA__idTac__4AB81AF0");

                    b.HasOne("DAL.Models.Tuasach", null)
                        .WithMany()
                        .HasForeignKey("IdTuaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CT_TACGIA__idTua__4BAC3F29");
                });

            modelBuilder.Entity("DAL.Models.Bcsachtratre", b =>
                {
                    b.HasOne("DAL.Models.Cuonsach", "IdCuonSachNavigation")
                        .WithMany("Bcsachtratre")
                        .HasForeignKey("IdCuonSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BCSACHTRA__idCuo__76969D2E");

                    b.Navigation("IdCuonSachNavigation");
                });

            modelBuilder.Entity("DAL.Models.CtBcluotmuontheotheloai", b =>
                {
                    b.HasOne("DAL.Models.Bcluotmuontheotheloai", "IdBaoCaoNavigation")
                        .WithMany("CtBcluotmuontheotheloai")
                        .HasForeignKey("IdBaoCao")
                        .IsRequired()
                        .HasConstraintName("FK__CT_BCLUOT__idBao__70DDC3D8");

                    b.HasOne("DAL.Models.Theloai", "IdTheLoaiNavigation")
                        .WithMany("CtBcluotmuontheotheloai")
                        .HasForeignKey("IdTheLoai")
                        .IsRequired()
                        .HasConstraintName("FK__CT_BCLUOT__idThe__71D1E811");

                    b.Navigation("IdBaoCaoNavigation");

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("DAL.Models.CtPhieunhap", b =>
                {
                    b.HasOne("DAL.Models.Sach", "IdSachNavigation")
                        .WithMany("CtPhieunhap")
                        .HasForeignKey("IdSach")
                        .IsRequired()
                        .HasConstraintName("FK__CT_PHIEUN__idSac__5DCAEF64");

                    b.HasOne("DAL.Models.Phieunhapsach", "SoPhieuNhapNavigation")
                        .WithMany("CtPhieunhap")
                        .HasForeignKey("SoPhieuNhap")
                        .IsRequired()
                        .HasConstraintName("FK__CT_PHIEUN__SoPhi__5CD6CB2B");

                    b.Navigation("IdSachNavigation");

                    b.Navigation("SoPhieuNhapNavigation");
                });

            modelBuilder.Entity("DAL.Models.Cuonsach", b =>
                {
                    b.HasOne("DAL.Models.Sach", "IdSachNavigation")
                        .WithMany("Cuonsach")
                        .HasForeignKey("IdSach")
                        .IsRequired()
                        .HasConstraintName("FK__CUONSACH__idSach__60A75C0F");

                    b.Navigation("IdSachNavigation");
                });

            modelBuilder.Entity("DAL.Models.Docgia", b =>
                {
                    b.HasOne("DAL.Models.Loaidocgia", "IdLoaiDocGiaNavigation")
                        .WithMany("Docgia")
                        .HasForeignKey("IdLoaiDocGia")
                        .IsRequired()
                        .HasConstraintName("FK__DOCGIA__idLoaiDo__5165187F");

                    b.HasOne("DAL.Models.Nguoidung", "IdNguoiDungNavigation")
                        .WithOne("Docgia")
                        .HasForeignKey("DAL.Models.Docgia", "IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__DOCGIA__idNguoiD__534D60F1");

                    b.Navigation("IdLoaiDocGiaNavigation");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("DAL.Models.Nguoidung", b =>
                {
                    b.HasOne("DAL.Models.Nhomnguoidung", "IdNhomNguoiDungNavigation")
                        .WithMany("Nguoidung")
                        .HasForeignKey("IdNhomNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NGUOIDUNG__idNho__403A8C7D");

                    b.Navigation("IdNhomNguoiDungNavigation");
                });

            modelBuilder.Entity("DAL.Models.Phieumuontra", b =>
                {
                    b.HasOne("DAL.Models.Cuonsach", "IdCuonSachNavigation")
                        .WithMany("Phieumuontra")
                        .HasForeignKey("IdCuonSach")
                        .IsRequired()
                        .HasConstraintName("FK__PHIEUMUON__idCuo__66603565");

                    b.HasOne("DAL.Models.Docgia", "IdDocGiaNavigation")
                        .WithMany("Phieumuontra")
                        .HasForeignKey("IdDocGia")
                        .IsRequired()
                        .HasConstraintName("FK__PHIEUMUON__idDoc__656C112C");

                    b.Navigation("IdCuonSachNavigation");

                    b.Navigation("IdDocGiaNavigation");
                });

            modelBuilder.Entity("DAL.Models.Phieuthu", b =>
                {
                    b.HasOne("DAL.Models.Docgia", "IdDocGiaNavigation")
                        .WithMany("Phieuthu")
                        .HasForeignKey("IdDocGia")
                        .IsRequired()
                        .HasConstraintName("FK__PHIEUTHU__idDocG__6A30C649");

                    b.Navigation("IdDocGiaNavigation");
                });

            modelBuilder.Entity("DAL.Models.Sach", b =>
                {
                    b.HasOne("DAL.Models.Tuasach", "IdTuaSachNavigation")
                        .WithMany("Sach")
                        .HasForeignKey("IdTuaSach")
                        .IsRequired()
                        .HasConstraintName("FK__SACH__idTuaSach__5629CD9C");

                    b.Navigation("IdTuaSachNavigation");
                });

            modelBuilder.Entity("DAL.Models.Tuasach", b =>
                {
                    b.HasOne("DAL.Models.Theloai", "IdTheLoaiNavigation")
                        .WithMany("Tuasach")
                        .HasForeignKey("IdTheLoai")
                        .IsRequired()
                        .HasConstraintName("FK__TUASACH__idTheLo__44FF419A");

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("Phanquyen", b =>
                {
                    b.HasOne("DAL.Models.Chucnang", null)
                        .WithMany()
                        .HasForeignKey("IdChucNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PHANQUYEN__idChu__3C69FB99");

                    b.HasOne("DAL.Models.Nhomnguoidung", null)
                        .WithMany()
                        .HasForeignKey("IdNhomNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PHANQUYEN__idNho__3B75D760");
                });

            modelBuilder.Entity("DAL.Models.Bcluotmuontheotheloai", b =>
                {
                    b.Navigation("CtBcluotmuontheotheloai");
                });

            modelBuilder.Entity("DAL.Models.Cuonsach", b =>
                {
                    b.Navigation("Bcsachtratre");

                    b.Navigation("Phieumuontra");
                });

            modelBuilder.Entity("DAL.Models.Docgia", b =>
                {
                    b.Navigation("Phieumuontra");

                    b.Navigation("Phieuthu");
                });

            modelBuilder.Entity("DAL.Models.Loaidocgia", b =>
                {
                    b.Navigation("Docgia");
                });

            modelBuilder.Entity("DAL.Models.Nguoidung", b =>
                {
                    b.Navigation("Docgia");
                });

            modelBuilder.Entity("DAL.Models.Nhomnguoidung", b =>
                {
                    b.Navigation("Nguoidung");
                });

            modelBuilder.Entity("DAL.Models.Phieunhapsach", b =>
                {
                    b.Navigation("CtPhieunhap");
                });

            modelBuilder.Entity("DAL.Models.Sach", b =>
                {
                    b.Navigation("CtPhieunhap");

                    b.Navigation("Cuonsach");
                });

            modelBuilder.Entity("DAL.Models.Theloai", b =>
                {
                    b.Navigation("CtBcluotmuontheotheloai");

                    b.Navigation("Tuasach");
                });

            modelBuilder.Entity("DAL.Models.Tuasach", b =>
                {
                    b.Navigation("Sach");
                });
#pragma warning restore 612, 618
        }
    }
}
